# Config file for automatic testing at travis-ci.org
sudo: false
dist: xenial
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_script: # code coverage tool
  - pip install -r tests/requirements.txt

install: 
  - pip install .

# command to run tests and save coverage
script:
  - python -m coverage run -m unittest discover -v

after_script:
  - python -m coverage report -m
  - python -m coverage xml

  - ./cc-test-reporter format-coverage --input-type coverage.py --debug
  - ./cc-test-reporter upload-coverage --debug
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

