# Config file for automatic testing at travis-ci.org
sudo: false
dist: xenial
language: python

git:
  depth: false

matrix:
  include:
  - python: pypy
    env: TESTS=tests.test_cached_property
  - python: 2.7
    env: TESTS=tests.test_cached_property
  - python: 3.4
    env: TESTS=tests.test_cached_property
  - python: 3.5
    env: TESTS=tests.test_cached_property
  - python: 3.6
    env: TESTS=tests
  - python: 3.7
    env: TESTS=tests

before_script:
  - pip install -r tests/requirements.txt

install: 
  - pip install .

script:
  - green $TESTS

after_success:
  - python -m coverage xml
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
  - althonosdev@gmail.com
